kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: httpd-pvc
  labels:
    name: httpd-pvc-l

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: html-rs
  labels:
    app: task3label-httpd
spec:
  replicas: 2
  selector:
    matchLabels:
       app: httpd
  template:
    metadata:
     name: myweb-pod-httpd
     labels:
       app: httpd
    spec:
      containers:
      - name:  httpd-os
        image: httpd
        volumeMounts:
        - name: task3vol-httpd
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: task3vol-httpd
        persistentVolumeClaim:
          claimName: httpd-pvc




