kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: php-pvc
  labels:
      name: php-pvc-label

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

kind: ReplicaSet
apiVersion: apps/v1

metadata:
  name: php-rs
  labels:
    app: task3label-php

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myphpapp
  template:
    metadata:
      name: php-pod
      labels:
        app: myphpapp
    spec:
      containers: 
      - name: php-os
        image: vimal13/apache-webserver-php
        volumeMounts:
        - name: myvol-1
          mountPath: /var/www/html
      volumes:
      - name: myvol-1
        persistentVolumeClaim:
          claimName: php-pvc







